/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YogaStyleRouteImport } from './routes/yoga/$style'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaStyleRoute = YogaStyleRouteImport.update({
  id: '/yoga/$style',
  path: '/yoga/$style',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/yoga/$style': typeof YogaStyleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/yoga/$style': typeof YogaStyleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/yoga/$style': typeof YogaStyleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/yoga/$style'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/yoga/$style'
  id: '__root__' | '/' | '/yoga/$style'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  YogaStyleRoute: typeof YogaStyleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga/$style': {
      id: '/yoga/$style'
      path: '/yoga/$style'
      fullPath: '/yoga/$style'
      preLoaderRoute: typeof YogaStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  YogaStyleRoute: YogaStyleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
